FROM nvcr.io/nvidia/cudagl:11.3.1-devel-ubuntu20.04

SHELL ["/bin/bash", "-c"]

RUN apt-get update && apt-get install -y git wget ssh && rm -rf /var/lib/apt/lists/* 

RUN apt-get update -q \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    curl \
    git \
    libgl1-mesa-dev \
    libgl1-mesa-glx \
    libglew-dev \
    libosmesa6-dev \
    software-properties-common \
    net-tools \
    vim \
    wget \
    xpra \
    xserver-xorg-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
# RUN conda install ffmpeg -y && conda clean -ya
# ENV GIT_SSH_COMMAND "ssh -i ~/.ssh/id_rsa_git"

ARG SSH_PRIVATE_KEY
RUN mkdir ~/.ssh/
RUN echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa_git
RUN chmod 600 ~/.ssh/id_rsa_git
RUN ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
RUN echo "Host github.com\n\tStrictHostKeyChecking no\n\tHostName github.com\n\tIdentityFile ~/.ssh/id_rsa_git" >> ~/.ssh/config
# RUN ssh-keyscan /github.com/ >> ~/.ssh/known_hosts

RUN cat ~/.ssh/config
RUN GIT_SSH_COMMAND="ssh -i /root/.ssh/id_rsa_git -o IdentitiesOnly=yes" git clone git@github.com:hzaskywalker/RPG.git ~/RPG

RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh && \
    chmod +x ~/miniconda.sh && \
    ~/miniconda.sh -b -u -p /opt/conda && \
    rm ~/miniconda.sh && \
    /opt/conda/bin/conda init && \
    /opt/conda/bin/conda install -y python=3.9 && \
    /opt/conda/bin/conda clean -ya
ENV PATH /opt/conda/bin:$PATH

RUN pip install --no-cache ninja cython 
RUN pip install --no-cache torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu113


# RUN git clone https://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@github.com/haosulab/pyrl.git
WORKDIR /root/RPG/
RUN git branch
RUN git checkout rpg
RUN cat setup.py

RUN pip install --no-cache wandb
RUN pip install --no-cache wandb
RUN pip install --no-cache yapf sorcery sapien tensorboardX pynvml lmdb


RUN mkdir -p /root/.mujoco \
    && wget https://mujoco.org/download/mujoco210-linux-x86_64.tar.gz -O mujoco.tar.gz \
    && tar -xf mujoco.tar.gz -C /root/.mujoco \
    && rm mujoco.tar.gz

ENV LD_LIBRARY_PATH /root/.mujoco/mujoco210/bin:${LD_LIBRARY_PATH}
ENV LD_LIBRARY_PATH /usr/local/nvidia/lib64:${LD_LIBRARY_PATH}
RUN pip install mujoco_py
RUN pip install tensorboardX
RUN pip install opencv-python
RUN pip install tqdm
RUN pip install gym==0.23.1
RUN pip install yacs>=0.1.8
RUN pip install matplotlib
RUN pip install transforms3d
RUN pip install h5py
RUN pip install moviepy

RUN python setup.py develop

RUN pip install pytorch3d --upgrade --no-cache -f https://dl.fbaipublicfiles.com/pytorch3d/packaging/wheels/py39_cu113_pyt1110/download.html



RUN pip install mujoco

RUN curl -o /usr/local/bin/patchelf https://s3-us-west-2.amazonaws.com/openai-sci-artifacts/manual-builds/patchelf_0.9_amd64.elf \
    && chmod +x /usr/local/bin/patchelf
RUN python3 -c "import gym; gym.make('HalfCheetah-v3')"
RUN pip install --no-cache scipy
RUN pip install --no-cache IPython